source: .
destination: ./_site
timezone: "Europe/Paris"
encoding: "utf-8"
show_drafts: false
future: true
detach: false
gems:
  - jekyll-asciidoc
asciidoctor:
  attributes:
    - hardbreaks!
    - icons=font
