---
layout: post
title: Bien gérer les arguments de son programme C en ligne de commande
---

= Bien gérer les arguments de son programme C en ligne de commande

Il est souvent nécessaire de gérer des arguments en ligne de commande. Mais en C, ce n'est pas toujours facile: il faut faire des boucles encombrantes, s'embêter avec les librairies standards comme `<string.h>`...
Aussi, apprenons à utiliser la petite bibliothèque *ArgLib*.

NOTE: La bibliothèque ArgLib est écrite en C, mais elle est tout à fait compilable comme du {cpp} et utilisable dans un programme {cpp}.

== 1. Intégration dans le programme

ArgLib se constitue de deux fichiers: `arglib.c` et `arglib.h`. Ajoutez les deux au dossier de votre programme.

=== 1.1. Obtention des fichiers sous un système GNU/Linux
Placez-vous dans le dossier de votre programme et exécutez:
....
wget https://raw.githubusercontent.com/paly2/ArgLib/master/arglib.c
wget https://raw.githubusercontent.com/paly2/ArgLib/master/arglib.h
....

[TIP]
====
Vous pouvez aussi cloner le dépôt au moyen de git:
....
sudo apt-get install git
git clone https://github.com/paly2/ArgLib.git
....
Ou encore télécharger l'archive .tar.gz et l'extraire:
....
wget https://github.com/paly2/ArgLib/archive/master.tar.gz
tar zxvf master.tar.gz
rm master.tar.gz
mv master ArgLib
....
Dans ces deux procédures, vous obtiendrez un dossier `ArgLib` qui contiendra les fichiers nécessaires, qu'il vous suffira de copier.
====

=== 1.2. Obtention des fichiers sous un système Windows

Utilisez https://github.com/paly2/ArgLib/archive/master.zip[ce lien] pour télécharger un fichier compressé .zip, qu'il vous suffira d'extraire pour récupérer les fichiers `arglib.h` et `arglib.c`.

=== 1.3. Inclusion

Il suffit maintenant d'inclure `arglib.h` :

[source,c]
----
#include <stdio.h>
#include "arglib.h"

int main(int argc, char *argv[]) {
	/* ... */
	return 0;
}
----

[CAUTION]
====
*N'oubliez pas les arguments de la fonction `main` !*

En effet, `int argc` et `char *argv[]` ne sont théoriquement pas obligatoires, mais ils contiennent les arguments du programme ! Ils vous sont donc indispensables.
====

== 2. Utilisation

=== 2.1. Savoir si un argument est passé

==== 2.1.1. Quelques précisions

Pour commencer, il faut savoir que la bibliothèque `ArgLib` partage les arguments en plusieurs catégories :

* Les arguments courts cumulables;
* Les arguments courts non cumulables;
* Les arguments longs;
* Les chemins de fichiers;
* Et les autres (arguments communs).

Chacun de ces types d'argument correspond à une valeur de l'énumération `arg_kind`, en portant respectivement le nom de :

* `SHORT`
* `SHORT_ONE`
* `LONG`
* `PATH`
* `COMMON`

NOTE: Il y a aussi une valeur `ERROR` dans l'énumération `arg_kind`, que nous verrons plus tard.

*Un argument court* est un argument qui se compose d'une seule lettre, précédé d'un tiret.

Les arguments courts peuvent être cumulés sur un même tiret... ou pas.
Généralement, les arguments courts "non cumulables" sont ceux qui doivent être suivis d'une valeur (nous verrson plus tard comment récupérer cette valeur). Par exemple, l'argument court `-o` du célèbre compilateur `gcc` doit être suivi d'un nom de fichier, ce qui explique qu'il ne soit pas "cumulable".

*Un argument long* est un argument qui se compose de plusieurs lettre (d'un mot, en fait), précédé de deux tirets. Ces arguments ne sont jamais cumulables. Ils sont parfois équivalents à un autre argument court: par exemple, un grand nombre de commandes possèdent un argument court `-h` équivalent à un argument long `--help` (qui a pour effet d'afficher de l'aide).

*Un chemin de fichier* est un chemin d'accès à un fichier.

INFO: La bibliothèque ArgLib considère qu'un argument est un chemin d'accès à un fichier uniquement si le fichier en question existe. Dans le cas contraire, l'argument sera considéré comme commun.

*Un argument commun* est un argument qui ne correspond à aucune des catégories vu précédemment.

==== 2.1.2. La fonction `char* arg_find(char *argv[], const char *arg, const arg_kind kind);`

Cette fonction prend trois paramètres: le tableau `argv` (rappellez-vous, c'est un argument passé à la fonction `main`), l'argument en question (celui dont on veut savoir s'il est passé), et le type d'argument (voir la section 2.1.1).
Elle retourne un pointeur sur l'argument entier où l'argument passé en second paramètre a été trouvé, ou NULL dans le cas d'une erreur.

NOTE: Dans le cas d'un argument court, seul le premier caractère de la chaîne de caractère passée en second paramètre ne sera pris en compte.

CAUTION: Dans le cas d'un argument court ou d'un argument long, vous ne devez pas écrire le(s) tiret(s) qui précédent l'argument.

IMPORTANT: La chaîne de caractère pointée par le pointeur retourné n'est pas forcément identique à l'argument passé en paramètre.

CAUTION: Vous ne pouvez pas passer le type `PATH` comme troisième paramètre.

NOTE: Vous pouvez passer plusieurs types à la fonction dans le troisième paramètre, par exemple `LONG|COMMON`.

=== 2.2. Trouver un argument qui en suit un autre

Vous vous souvenez de l'exemple de l'argument `-o` de `gcc` ? Il est toujours suivi d'un autre argument. La bibliothèque ArgLib vous permet facilement d'obtenir un tel argument au moyen de la fonction `char* arg_followed(char *argv[], char *previous);`.

Elle prend comme premier paramètre le tableau `argv`, et comme second paramètre l'argument précédent. Elle retourne un pointeur sur l'argument suivant.

WARNING: Le second paramètre de cette fonction *doit* être un pointeur retourné par la fonction `arg_find` ! Ou, au moins, un pointeur du tableau `argv`. Si vous ne le faites pas, dans le meilleur des cas, la fonction vous retournera n'importe quoi, dans le pire des cas, elle entraînera une erreur de segmentation.

=== 2.3. Trouver un chemin vers un fichier/dossier

Il existe une fonction - d'utilité limitée, certes - qui vous permet de trouver un chemin vers un fichier ou vers un dossier. J'ai nommé `char* arg_find_pathname(char *argv[], const int flags);`.

Elle prend comme premier paramètre le tableau `argv`, et comme second paramètre, soit:

* `arg_FILENAME`: L'argument correspond à un fichier.
* `arg_DIRNAME`: L'argument correspond à un dossier.
* `arg_DIRNAME|arg_FILENAME`: L'argument correspond à un fichier, ou à un dossier.

Elle retourne un pointeur sur le premier chemin correspondant trouvé.

=== 2.4. Connaître la "catégorie" d'un argument

Parfois, il peut aussi être utile de savoir si un argument est court, long...
Cela peut se faire au moyen de la fonction `arg_kind arg_how_is(const char *arg);`.

Dans ce prototype, vous pouvez reconnaître l'énumération `arg_kind`. En effet, à partir de la chaîne de caractère qui lui est passée en argument, la fonction `arg_how_is` retourne la catégorie de l'argument (à savoir `SHORT`, `SHORT_ONE`, `LONG`, `PATH`, `COMMON`, ou encore `ERROR` dans le cas d'une erreur.
