---
layout: post
title: Héberger son site Web chez sois avec le serveur HTTP nginx
---

= Héberger son site Web chez sois avec le serveur HTTP nginx
Beaucoup d'entre vous veulent certainement héberger leur site web sur leur propre serveur. Nous allons voir ici comment procéder.

== 1. Pourquoi nginx ?

Nginx (si quelqu'un sait comment le prononcer, je l'invite à m'en faire part au moyen de l'adresse e-mail indiquée dans le pied-de-page) est le serveur HTTP que je vous propose d'utiliser, en raison de ses incroyables performances.

____
Nginx est difficile à mettre en place.
____

On entend parfois cette phrase, ce qui rebute certains à l'utiliser (qui finissent avec un Apache dévorreur de RAM). Comme vous allez pouvoir vous en rendre compte au cours de ce tutoriel, c'est faux.

== 2. Situation de départ

À ce stade, j'estime que vous avez :

* Un PC serveur avec un système d'exploitation Debian,
* Un site web tout frais tout chaud qui n'attend que d'être servi quelque part sur votre PC serveur,
* Un minimum de connaissances en systèmes UNIX.

IMPORTANT: L'ensemble du tutoriel est fait sous Debian. Il n'a pas été testé sous Ubuntu ou sous Raspbian ; cependant, comme il s'agit de dérivées de Debian, je suppose que ce tutoriel peut tout à fait s'y appliquer - éventuellement au prix de changements minimes. Par contre, n'espérez pas l'utiliser pour un système Microsoft Windows.

== 3. Mise en place de nginx

IMPORTANT: Toutes les actions de cette section doivent être exécutées sur le PC serveur.

=== 3.1. Installation

Difficile de faire plus simple:
....
# apt-get install nginx
....

Ensuite, rendez-vous à http://localhost[cette adresse] (toujours depuis le PC serveur!), et vérifiez que vous n'obtenez pas d'erreur - et que vous voyez une page qui vous informe que nginx a correctement été installé.

=== 3.2. Configuration

Les fichiers de configuration de nginx doivent normallement se trouver dans /etc/nginx. Si ce dossier n'existe pas, essayez /usr/local/nginx(/conf) ou encore /usr/local/etc/nginx.

Placez-vous dans ce dossier et exécutez la commande `ls`. Parmi la liste retournée, vérifiez que le dossier sites-enabled s'y trouve, et entrez-y d'un coup de `cd sites-enablds`. Exécutez à nouveau `ls`.

Et là, normallement, ô bonheur, un exemple de configuration s'y trouve déjà: le fichier `default` !
Copiez-le avec un nom plus parlant pour vous (par exemple `cp default my_website`). Vous pouvez ensuite déplacer le fichier default (voire le supprimer, vu que vous devriez avoir une copie dans site-availables/default) ; en tous cas, ne le laissez pas dans sites-enabled.

Éditez maintenant votre nouveau fichier avec votre éditeur préféré.
Cherchez la ligne `root /var/www/html;`, et remplacez `/var/www/html` par l'emplacement de votre site web.
Cherchez aussi la ligne `server_name __;`, et remplacez `__` par l'adresse de votre site (c'est optionnel mais recommandé).

Finalement, exécutez:
....
# nginx -s reload
....

Pour recharger les fichiers de configuration. Revenez à http://localhost[cette adresse] et... magie ! Votre site web s'y affiche !

Voilà, c'est finit avec la configuration de nginx. Quand je vous disais que ce n'était pas difficile.

== 4. Configuration du réseau

=== 4.1. Donner à votre PC serveur une IP locale statique

Alors maintenant ça marche très bien en localhost, mais si vous voulez accéder à votre ordinateur dans votre réseau local de façon fiable et statique (c'est-à-dire que son IP ne change pas (qu'il n'utilise pas le DHCP)), il va falloir toucher au fichier de configuration `/etc/network/interfaces` - que vous pouvez vous empresser d'ouvrir avec votre éditeur de texte préféré.

Cherchez une ligne qui ressemble à:
....
iface eth0 inet dhcp
....

IMPORTANT: `eth0` peut être remplacé par `eth1` ou autre `ethX` si vous n'utilisez pas le premier port Ethernet. En revanche, pour un serveur, il est fortement déconseillé d'utiliser une connexion WiFi: faites donc attention aux `wlan0`, `wlan1`, etc.

Et remplacez-la par tout ce bloc:
....
iface eth0 inet static
address 192.168.1.101
netmask 255.255.255.0
gateway 192.168.1.1
....

TIP: Ici je vous fait utiliser l'adresse statique 192.168.1.101, parce que généralement les IP DHCP sont attribuées de 192.168.1.2 à 192.168.1.100. Mais rien ne vous empêche de choisir autre chose! De même, l'adresse de la gateway (votre routeur) est ici 192.168.1.1, mais dans un réseau complexe il peut s'agir de quelque chose de complètement différent (enfin, dites-vous que si vous n'avez aucune idée de que la gateway pourrait être, c'est que c'est très certainement 192.168.1.1). Même chose pour le netmask (masque de sous-réseau)...

Puis exécutez:
....
sudo /etc/init.d/networking restart
....

Maintenant, vous pouvez accéder à votre serveur n'importe où depuis votre réseau local, en utilisant le lien http://192.168.1.101 !

=== 4.2. Rediriger les requêtes sur le port 80 en provenance de l'extérieur vers votre serveur

Rendez-vous, depuis votre réseau local, à http://192.168.1.1[l'adresse gateway]. Normalement, vous obtenez la page de configuration du routeur.

Il va falloir que vous vous débrouilliez pour rediriger les requêtes sur le port 80 en provenance de l'extérieur vers votre serveur (donc si vous avez utilisé la configuration d'IP statique de la section précédente, vers la machine à l'adresse 192.168.1.101).

Pour faire cela, la procédure diffère selon les routeurs. Vous pouvez faire une recherche sur le Web pour l'obtenir. Généralement, vous devez chercher un onglet NAT.

== 5. Fin et suite

Maintenant, votre site est accessible de partout au moyen de votre adresse IP.

Je comprendrais tout à fait que vous ne vous contentiez pas de votre adresse IP, et que vous aimeriez un nom de domaine - surtout si celle-ci est dynamique. Mais cela dépasse les ambitions de ce petit tutoriel, qui était simplement censé expliquer comment configurer nginx.
Cependant, je vous laisse quelques liens qui pourront vous aider:

* https://noip.com : pour obtenir un DNS dynamique gratuit avec un sous-domaine et/ou un vrai nom de domaine (payant).
* https://www.gandi.net : pour obtenir un nom de domaine (payant).
* http://www.dot.tk : pour obtenir un vrai nom de domaine gratuit en .tk.

